apiVersion: apps/v1
kind: Deployment
metadata:
  name: desafio-mysql 
spec:
  selector:
    matchLabels:
      app: desafio-mysql
  template:
    metadata:
      labels: 
        app: desafio-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
          - containerPort: 3306
          args: 
            - "--ignore-db-dir=lost+found"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-user-pass
                  key: password

          volumeMounts:
            - name: mysql-volume
              mountPath: /var/lib/mysql

      volumes:
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: mysql-pv


