apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data: 
  nginx.conf: |
      server {
        listen 80;
        index index.php index.html;
        root /usr/share/nginx/html;
      }
  index.html: "<h1>Code.education Rocks</h1>"