apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-hello
  template:
    metadata:
      labels:
        app: nginx-hello
    spec:
      containers:
        - name: nginx 
          image: nginx:1.17-alpine
          ports:
          - containerPort: 80

          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: index-html
             
            - mountPath: /etc/nginx/conf.d
              name: nginx-conf
              readOnly: true

      volumes:
       - name: nginx-conf
         configMap:
          name: config
          items:
            - key: nginx.conf
              path: nginx.conf
       - name: index-html
         configMap:
          name: config
          items:
            - key: index.html
              path: index.html