apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-go
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: app-go
  template:
    metadata:
      labels:
        app: app-go

    spec:
      containers:
      - name: app-go
        image: img_app_go
        ports:
        - containerPort: 8000

